_wandb:
    value:
        cli_version: 0.21.0
        e:
            isxzjy4tefz3xosni9be5kv5mfyd25jc:
                args:
                    - --model_name
                    - deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
                    - --train_size
                    - "500"
                    - --eval_size
                    - "100"
                    - --num_epochs
                    - "8"
                    - --early_stopping_patience
                    - "4"
                    - --learning_rate
                    - "5e-8"
                    - --left_clip_range
                    - "2e-3"
                    - --right_clip_range
                    - "2e-3"
                    - --grad_accum_steps
                    - "4"
                    - --use_curriculum
                    - --use_wandb
                codePath: train_robust_gspo.py
                codePathLocal: train_robust_gspo.py
                cpu_count: 40
                cpu_count_logical: 40
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "266206101504"
                        used: "200481521664"
                email: domainluther1234@gmail.com
                executable: /home/azureuser/gpso/myenv/bin/python
                git:
                    commit: 10fab70b5f27b4d577846541b3397204ba5fdaaf
                    remote: https://github.com/vivekvar-dl/gpso.git
                gpu: NVIDIA H100 NVL
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-8f343f96-d9d0-2be5-c0eb-73e8c6d74144
                host: vivek22
                memory:
                    total: "337898176512"
                os: Linux-6.8.0-1031-azure-x86_64-with-glibc2.35
                program: /home/azureuser/gpso/train_robust_gspo.py
                python: CPython 3.10.12
                root: /home/azureuser/gpso
                startedAt: "2025-07-31T06:15:29.663704Z"
                writerId: isxzjy4tefz3xosni9be5kv5mfyd25jc
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.12
            "5": 0.21.0
            "6": 4.54.1
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 2
curriculum_threshold:
    value: 0.6
early_stopping_patience:
    value: 4
eval_size:
    value: 100
grad_accum_steps:
    value: 4
group_size:
    value: 4
learning_rate:
    value: 5e-08
left_clip_range:
    value: 0.002
max_length:
    value: 512
model_name:
    value: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
num_epochs:
    value: 8
output_dir:
    value: ./robust_gspo_results
right_clip_range:
    value: 0.002
seed:
    value: 42
train_size:
    value: 500
update_frequency:
    value: 1
use_curriculum:
    value: true
use_wandb:
    value: true
val_split:
    value: 0.1
