_wandb:
    value:
        cli_version: 0.21.0
        e:
            9x4z24cxqnde2ehxma7b4jne6xcqzs94:
                args:
                    - --dataset
                    - gsm8k
                    - --num_train_samples
                    - "200"
                    - --num_epochs
                    - "3"
                    - --batch_size
                    - "2"
                    - --group_size
                    - "4"
                    - --learning_rate
                    - "2e-08"
                    - --left_clip_range
                    - "0.002"
                    - --right_clip_range
                    - "0.002"
                    - --update_frequency
                    - "1"
                    - --max_length
                    - "512"
                    - --output_dir
                    - ./experiments/gspo_exp_1
                    - --use_wandb
                codePath: train_gspo.py
                codePathLocal: train_gspo.py
                cpu_count: 40
                cpu_count_logical: 40
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "266206101504"
                        used: "167435280384"
                email: domainluther1234@gmail.com
                executable: /home/azureuser/gpso/myenv/bin/python
                git:
                    commit: e31c5656d47ce7210f92a3e978ad0e7d6d5b184c
                    remote: https://github.com/vivekvar-dl/gpso.git
                gpu: NVIDIA H100 NVL
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-8f343f96-d9d0-2be5-c0eb-73e8c6d74144
                host: vivek22
                memory:
                    total: "337898176512"
                os: Linux-6.8.0-1031-azure-x86_64-with-glibc2.35
                program: /home/azureuser/gpso/train_gspo.py
                python: CPython 3.10.12
                root: /home/azureuser/gpso
                startedAt: "2025-07-31T04:25:19.011666Z"
                writerId: 9x4z24cxqnde2ehxma7b4jne6xcqzs94
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "3":
                - 13
                - 16
                - 61
            "4": 3.10.12
            "5": 0.21.0
            "6": 4.54.1
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 2
dataset:
    value: gsm8k
device:
    value: cuda
eval_frequency:
    value: 20
group_size:
    value: 4
learning_rate:
    value: 2e-08
left_clip_range:
    value: 0.002
log_frequency:
    value: 5
max_length:
    value: 512
mini_batch_size:
    value: 1
model_name:
    value: Qwen/Qwen2.5-7B-Instruct
num_epochs:
    value: 3
num_eval_samples:
    value: 20
num_train_samples:
    value: 200
output_dir:
    value: ./experiments/gspo_exp_1
right_clip_range:
    value: 0.002
seed:
    value: 42
update_frequency:
    value: 1
use_wandb:
    value: true
